// Language code to full name mapping
export const LANGUAGE_NAMES: Record<string, string> = {
  // Remove quotes if they exist in the data
  '"en"': "English",
  '"es"': "Spanish",
  '"fr"': "French",
  '"de"': "German",
  '"it"': "Italian",
  '"pt"': "Portuguese",
  '"zh"': "Chinese",
  '"ja"': "Japanese",
  '"ko"': "Korean",
  '"ru"': "Russian",
  '"ar"': "Arabic",
  '"th"': "Thai",
  '"id"': "Indonesian",
  '"km"': "Khmer",
  '"lo"': "Lao",
  '"pl"': "Polish",
  '"hu"': "Hungarian",
  '"mn"': "Mongolian",
  '"ro"': "Romanian",
  '"tr"': "Turkish",
  '"vi"': "Vietnamese",
  '"nl"': "Dutch",
  '"sv"': "Swedish",
  '"da"': "Danish",
  '"no"': "Norwegian",
  '"fi"': "Finnish",

  // Without quotes (in case data is fixed)
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  ru: "Russian",
  ar: "Arabic",
  th: "Thai",
  id: "Indonesian",
  km: "Khmer",
  lo: "Lao",
  pl: "Polish",
  hu: "Hungarian",
  mn: "Mongolian",
  ro: "Romanian",
  tr: "Turkish",
  vi: "Vietnamese",
  nl: "Dutch",
  sv: "Swedish",
  da: "Danish",
  no: "Norwegian",
  fi: "Finnish",
};

export function getLanguageName(code: string): string {
  return LANGUAGE_NAMES[code] || code.replace(/"/g, '').toUpperCase();
}
